---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: rhem-cli-web-terminal
spec:
  output:
    to:
      kind: ImageStreamTag
      name: rhem-cli-web-terminal:latest

  strategy:
    type: Docker

  source:
    type: Dockerfile
    dockerfile: |
      ARG BASE_IMAGE
      FROM ${BASE_IMAGE}
      USER 0
      RUN curl -L https://github.com/flightctl/flightctl/releases/download/{{ .Values.rhemVersion }}/flightctl-linux-amd64 --output /usr/local/bin/flightctl
      RUN chmod +x /usr/local/bin/flightctl