---
apiVersion: 'kubevirt.io/v1'
kind: 'VirtualMachine'
metadata:
  annotations:
    vm.kubevirt.io/validations: "[\n  {\n    \"name\": \"minimal-required-memory\",\n    \"path\": \"jsonpath::.spec.domain.memory.guest\",\n    \"rule\": \"integer\",\n    \"message\": \"This VM requires more memory.\",\n    \"min\": 1610612736\n  }\n]\n"
  labels:
    app: 'rhem-virtual-machine'
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: 'rhel9-server-small'
    vm.kubevirt.io/template.namespace: 'openshift'
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: 'v0.34.1'
  name: 'rhem-virtual-machine'
spec:
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        name: 'rhem-virtual-machine'
      spec:
        sourceRef:
          kind: 'DataSource'
          name: 'rhel9'
          namespace: 'openshift-virtualization-os-images'
        storage:
          resources:
            requests:
              storage: '70Gi'
  runStrategy: 'RerunOnFailure'
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: 'small'
        vm.kubevirt.io/os: 'rhel9'
        vm.kubevirt.io/workload: 'server'
      labels:
        kubevirt.io/domain: 'rhem-virtual-machine'
        kubevirt.io/size: 'small'
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - {{ include "rhem-virtual-machine.determineWorker" (list $.Values.rhemVirtualMachine.username $.Values.guid $.Values.virtualMachinesPerWorker) }}
      architecture: 'amd64'
      domain:
        cpu:
          cores: 1
          sockets: 4
          threads: 1
        devices:
          blockMultiQueue: true
          disks:
            - disk:
                bus: 'virtio'
              name: 'rootdisk'
              cache: writethrough
            - disk:
                bus: 'virtio'
              name: 'cloudinitdisk'
          interfaces:
            - masquerade: {}
              model: 'virtio'
              name: 'default'
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: 'pc-q35-rhel9.6.0'
        memory:
          guest: '8Gi'
      networks:
        - name: 'default'
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: 'rhem-virtual-machine'
          name: 'rootdisk'
        - cloudInitNoCloud:
            {{- with .Values.rhemVirtualMachine }}
            userData: "#cloud-config\nuser: {{ .username }}\npassword: {{ .password }}\nchpasswd: { expire: False }\nssh_pwauth: true"
            {{- end }}
          name: 'cloudinitdisk'
