---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bastion-ansible-job-inputs
data:
  inventory.yaml: |
    ---
    all:
      hosts:
        bastion:
          ansible_user: admin
          ansible_password: {{ .Values.bastionSshPassword }}
          ansible_host: bastion-ssh.bastion.svc.cluster.local
          ansible_become: true

  playbook.yaml: |
    ---
    - name: Setup user on bastion host
      hosts:
        - all
      gather_facts: false
      pre_tasks:
        - name: Wait for VM to be up
          ansible.builtin.wait_for_connection:
            timeout: 600
      tasks:
        - name: Create user account
          ansible.builtin.user:
            name: "{{ .Values.guid }}-{{ .Values.tenant }}"
            create_home: true
            generate_ssh_key: true
            password: "{{- "{{" }} '{{ .Values.bastionSshPassword }}' | password_hash('sha512', 'rhem') {{ "}}" }}"
            state: present
        - name: Remove other MOTD files
          ansible.builtin.file:
            path: "/etc/motd.d/{{- "{{" }} file {{ "}}" }}"
            state: absent
          loop:
            - insights-client
            - cockpit
          loop_control:
            loop_var: file
        - name: Toss MOTD file in user's .bash_profile
          ansible.builtin.blockinfile:
            path: /home/{{ .Values.guid }}-{{ .Values.tenant }}/.bash_profile
            insertafter: EOF
            block: |
              echo "Hello {{ .Values.guid }}-{{ .Values.tenant }}!"
              echo ""
              echo "Your RHEM virtual machine is available at: rhem-on-rhel-ssh.wksp-{{ .Values.guid }}-{{ .Values.tenant }}.svc.cluster.local"
              echo ""
              echo "Use the following credentials:"
              echo "Username: {{ .Values.guid }}-{{ .Values.tenant }}"
              echo "Password: {{ .Values.bastionSshPassword }}"
              echo ""
              echo "To connect, use the following command:"
              echo "ssh {{ .Values.guid }}-{{ .Values.tenant }}@rhem-on-rhel-ssh.wksp-{{ .Values.guid }}-{{ .Values.tenant }}.svc.cluster.local"
