---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.guid }}-{{ .Values.tenant }}-rhem-virtual-machine
  namespace: openshift-gitops
  labels:
    application: {{ .Values.guid }}-{{ .Values.tenant }}-rhem-virtual-machine
    guid.rhdp.io: {{ .Values.guid }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    server: https://kubernetes.default.svc
    namespace: wksp-{{ .Values.guid }}-{{ .Values.tenant }}
  project: default
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://github.com/rhpds/edge-fleet-gitops.git
    targetRevision: rh1-2026
    path: tenant/rhem-virtual-machine/
    helm:
      values: |
        gitBranch: rh1-2026
        rhemVirtualMachine:
          username: {{ .Values.tenant }}
          password: {{ .Values.bastionSshPassword }}
        satelliteActivationKey: "{{ .Values.satelliteActivationKey }}"
        satelliteOrg: "{{ .Values.satelliteOrg }}"
        satelliteUrl: "{{ .Values.satelliteUrl }}"
        guid: "{{ .Values.guid }}"
        virtualMachinesPerWorker: 10