---
apiVersion: v2
name: drone-virtual-machine
description: > 
  This chart creates supporting resources for the drone VM. Note - it does not create the VM itself, the students create it when going through the exercises.
version: 1.0.0
appVersion: "1.0.0"
