---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ocp-build-bootc
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: minimal-bootc
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: minimal-bootc-rechunked