---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-repo
data:
  flightctl.repo: |
    [flightctl]
    name=Flight Control RPM Repository (EPEL)
    type=rpm-md
    baseurl=https://rpm.flightctl.io/epel/9/$basearch/
    gpgcheck=1
    gpgkey=https://download.copr.fedorainfracloud.org/results/@redhat-et/flightctl/pubkey.gpg
    enabled=1
    enabled_metadata=1
    metadata_expire=1d