---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bootc-image-builder-config
data:
  config.toml: |
    [[customizations.user]]
    name = "student"
    password = "{{ .Values.user_password }}"
    groups = ["wheel"]
    [customizations.kernel]
    name = "disable-selinux"
    append = "selinux=0"

