---
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-{{ .Values.guid }}-load-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app.kubernetes.io/name: deploy-load-test
    app.kubernetes.io/part-of: load-test
spec:
  backoffLimit: 20
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deploy-load-test
        app.kubernetes.io/part-of: load-test
    spec:
      restartPolicy: OnFailure
      containers:
        - name: run-ansible-playbook
          image: quay.io/jswanson/general-ansible-ee:rh1-2026
          imagePullPolicy: Always
          command: ["ansible-playbook", "/runner/playbook.yaml", "--inventory", "/runner/inventory.yaml", "-vv"]
          volumeMounts:
            - name: inventory
              mountPath: /runner/inventory.yaml
              subPath:  inventory.yaml
            - name: playbook
              mountPath: /runner/playbook.yaml
              subPath: playbook.yaml
            - name: template
              mountPath: /runner/override.facts.j2
              subPath: override.facts.j2
            - name: inventory-to-deploy
              mountPath: /runner/inventory-to-deploy.yaml
              subPath:  inventory-to-deploy.yaml
            - name: playbook-to-deploy
              mountPath: /runner/playbook-to-deploy.yaml
              subPath: playbook-to-deploy.yaml
            - name: ansible-cfg-to-deploy
              mountPath: /runner/ansible-cfg-to-deploy.cfg
              subPath: ansible-cfg-to-deploy.cfg
            - name: scratch
              mountPath: /.ansible
      volumes:
        - name: inventory
          configMap:
            name: load-test-{{ .Values.guid }}-ansible-inputs
        - name: playbook
          configMap:
            name: load-test-{{ .Values.guid }}-ansible-inputs
        - name: inventory-to-deploy
          configMap:
            name: load-test-{{ .Values.guid }}-ansible-inputs
        - name: playbook-to-deploy
          configMap:
            name: load-test-{{ .Values.guid }}-ansible-inputs
        - name: template
          configMap:
            name: load-test-{{ .Values.guid }}-ansible-inputs
        - name: ansible-cfg-to-deploy
          configMap:
            name: load-test-{{ .Values.guid }}-ansible-inputs
        - name: scratch
          emptyDir: {}