---
apiVersion: v1
kind: ConfigMap
metadata:
  name: janitor-ansible-job-inputs
data:
  playbook.yaml: |
    ---
    - name: Cleanup Gitea and Oauth
      hosts:
        - localhost
      gather_facts: false
      connection: local
      vars:
        oauth_identity_name: {{ .Values.guid }}-htpasswd
        oauth_state: absent
      tasks:
        - name: Delete user from Gitea
          ansible.builtin.uri:
            url: "https://gitea.{{ .Values.openshiftClusterIngressDomain }}/api/v1/admin/users/{{ "{{" }} user {{ "}}" }}?purge=true"
            headers:
              Content-Type: application/json
            force_basic_auth: true
            url_username: "{{ .Values.giteaAdminUsername }}"
            url_password: "{{ .Values.giteaAdminPassword }}"
            method: DELETE
            status_code:
              - 200
              - 204
              - 404
          loop:
            {{- $userCount := int .Values.user.count }}
            {{- range $index := until $userCount }}
            - {{ $.Values.guid }}-{{ $.Values.user.prefix }}{{ add $index 1 }}
            {{- end }}
          loop_control:
            loop_var: user
        - name: Read current OAuth config
          kubernetes.core.k8s_info:
            api_version: config.openshift.io/v1
            kind: OAuth
            name: cluster
          register: oauth
        - name: Extract identityProviders list
          ansible.builtin.set_fact:
            identity_providers: "{{- "{{" }} oauth.resources[0].spec.identityProviders {{ "}}" }}"
        - name: Check if provider already exists
          ansible.builtin.set_fact:
            provider_exists: >-
              {{ "{{" }}
                identity_providers
                | selectattr('name', 'equalto', oauth_identity_name)
                | list
                | length > 0
              {{ "}}" }}
        - name: Remove provider entry (if state=absent and exists)
          ansible.builtin.set_fact:
            identity_providers: >-
              {{ "{{" }}
                identity_providers
                | rejectattr('name', 'equalto', oauth_identity_name)
                | list
              {{ "}}" }}
          when:
            - oauth_state == "absent"
            - provider_exists
        - name: Apply updated OAuth config ONLY if changes occurred
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: config.openshift.io/v1
              kind: OAuth
              metadata:
                name: cluster
              spec:
                identityProviders: "{{- "{{" }} identity_providers {{ "}}" }}"
          when:
            - provider_exists
            - oauth_state == "absent"
    - name: Cleanup the bastion host
      hosts:
        - bastion
      gather_facts: false
      become: true
      tasks:
        - name: Create user account
          ansible.builtin.user:
            name: "{{- "{{" }} user {{ "}}" }}"
            state: absent
          loop:
            {{- $userCount := int .Values.user.count }}
            {{- range $index := until $userCount }}
            - {{ $.Values.guid }}-{{ $.Values.user.prefix }}{{ add $index 1 }}
            {{- end }}
          loop_control:
            loop_var: user
        - name: Remove home folder
          ansible.builtin.file:
            path: "/home/{{- "{{" }} folder {{ "}}" }}"
            state: absent
          loop:
            {{- $userCount := int .Values.user.count }}
            {{- range $index := until $userCount }}
            - {{ $.Values.guid }}-{{ $.Values.user.prefix }}{{ add $index 1 }}
            {{- end }}
          loop_control:
            loop_var: folder

  inventory.yaml: |
    ---
    all:
      hosts:
        bastion:
          ansible_user: admin
          ansible_password: {{ .Values.bastionSshPassword }}
          ansible_host: bastion-ssh.bastion.svc.cluster.local
          ansible_become: true