---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhem-agent-config-creater-role
rules:
  - apiGroups: ["route.openshift.io"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]