---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-job-inputs
data:
  inventory.yaml: |
    ---
    all:
      hosts:
        bastion:
          ansible_user: admin
          ansible_password: {{ .Values.bastion.password }}
          ansible_host: bastion-ssh.bastion.svc.cluster.local

  playbook.yaml: |
    ---
    - name: Initial setup of the bastion host
      hosts:
        - all
      gather_facts: false
      pre_tasks:
        - name: Wait for VM to be up
          ansible.builtin.wait_for_connection:
            timeout: 600
      tasks:
        - name: Enable/start Cockpit
          ansible.builtin.systemd:
            name: cockpit.socket
            state: started
            enabled: true
  
  ansible.cfg: |
    [defaults]
    host_key_checking = False
